name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22.0'
          cache: true

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm gcc g++ make gcc-mingw-w64 g++-mingw-w64 gcc-multilib
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Install SSH key for AUR
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.AUR_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Install xcaddy
        run: |
          echo "Installing xcaddy..."
          XCADDY_PATH=$(which xcaddy)
          echo "xcaddy installed at: $XCADDY_PATH"
          xcaddy version

      - name: Set up build environment
        run: |
          make setup
      - name: Build Veil
        run: |
          make build
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: 2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          CGO_ENABLED: 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/* 